---
title: "Thomas Van Hoey"
subtitle: "List of Publications"
output:
  pdf_document: 
    latex_engine: xelatex
  html_document: default
CJKmainfont: Noto Sans CJK TC
sansfont: Georgia
mainfont: Noto Serif # Noto Serif
header-includes:
  - \usepackage{xparse}   # needed for defining commands with lists
  - \usepackage{fontawesome5}
  - \newcommand{\iconspace}{\quad}
  - \NewDocumentCommand{\iconset}{>{\SplitList{,}}m}{\textcolor[gray]{0.4}{\footnotesize\ProcessList{#1}{\iconitem}}}
  - \newcommand{\iconitem}[1]{#1\iconspace}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Refereed articles

<!-- \iconset{ \faLightbulb \, \faClipboardList \,  \faChartLine \,  \faPenNib \,  \faUserCheck \, \faAt } -->


\fbox{%
\parbox{1\linewidth}{%

\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lll}
\faLightbulb \quad conception and design &
\faClipboardList \quad data collection &
\faChartLine \quad analysis and interpretation \\
\faPenNib \quad manuscript drafting &
\faUserCheck \quad single author &
\faAt \quad corresponding author \\
\end{tabular*}%
}%
}

(@) **Van Hoey, Thomas**, Matt. H. Gardner, Ruiming Ma & Benedikt Szmrecsanyi.
*accepted*.
Unpredictable grammatical choices are not harder than predictable ones.
Language Variation and Change.
\iconset{ \faLightbulb \,   \faChartLine \,  \faPenNib \,   \faAt }


(@)
**Van Hoey, Thomas**, Benedikt Szmrecsanyi, Matt Hunt Gardner. Choice and complexity: Debunking the myth that absolute complexity invariably leads to relative complexity.
*accepted*.
Linguistic Typology at the Crossroads - special issue
\iconset{\faLightbulb \, \faChartLine \, \faPenNib \,  \faAt}

(@)
**Van Hoey, Thomas**. 2025. Dynamic extensions of iconic form-meaning mappings in visual media, viewed through a prismatic lens.
*SKASE Journal of Theoretical Linguistics* 22(2). 
110-127.
\iconset{ \faUserCheck \, \faAt }
<!-- [url]() STILL NEED TO ADD -->

(@)
**Van Hoey, Thomas**\*, Arthur Lewis Thompson\*, Aaron Wing Cheung Chik & Youngah Do. 
2025 (online).
Iconic hand gestures from ideophones exhibit stability and emergent phonological properties: An iterated learning study.
*Cognitive Linguistics*  36(2). 227-259.
[doi:10.1515/cog-2024-0033](https://doi.org/10.1515/cog-2024-0033)
\* co-first authors 
\iconset{\faLightbulb \, \faClipboardList \, \faChartLine\,  \faPenNib }

(@)
Ma, Ruiming, **Thomas Van Hoey** & Benedikt Szmrecsanyi. 2025.
Isomorphism-inspired theorising about optionality and variation is unsupported by data from English grammar.
*English Language and Linguistics*. 1-21.
[doi:10.1017/S1360674325000097](https://doi.org/10.1017/S1360674325000097).
\iconset{ \faChartLine \, \faPenNib }

(@)
**Van Hoey, Thomas**. 2025.
Waddling, wandering and waving: Literary Chinese ideophones and the Motion Semantic Grid.
*Cognitive Semantics* (special issue on Talmyan motion semantics). 11(2).
1-29.
[doi:10.1163/23526416-bja10075](https://brill.com/view/journals/cose/11/2/article-p1_001.xml).
\iconset{ \faUserCheck \, \faAt }

(@)
Sze, Samuel Sui Lung, Xiaoyu Yu, **Thomas Van Hoey**, Bingzi Yu & Youngah Do. 
2025 (online).
Bilinguals’ advantages in executive function: Learning phonotactics and alternation.
*Second Language Research*. 1-30.
[doi: 10.1177/02676583251327097](https://journals.sagepub.com/doi/10.1177/02676583251327097)
\iconset{ \faChartLine \, \faPenNib }

<!-- full reference complete -->

(@)
Yu, Xiaoyu, **Thomas Van Hoey**, Frank Lihui Tan, Baichen Du & Youngah Do. 2024. Tracking phonological regularities: Exploring the influence of learning mode and regularity locus in adult phonological learning.  *Linguistics Vanguard* 10(1). 93-104. [doi: 10.1515/lingvan-2023-0050](https://doi.org/10.1515/lingvan-2023-0050)
\iconset{ \faLightbulb \, \faClipboardList \, \faChartLine \, \faPenNib  }

(@)
**Thomas Van Hoey**, Xiaoyu Yu, Tungle Pan & Youngah Do. 2024. What ratings and corpus data reveal about the vividness of Mandarin ABB words. *Language and Cognition* 16(4). 1674-1696. [doi: 10.1017/langcog.2024.22](https://doi.org/10.1017/langcog.2024.22)
\iconset{ \faLightbulb \, \faClipboardList \,  \faChartLine \,  \faPenNib  }

(@)
**Van Hoey, Thomas**, Arthur Lewis Thompson,  Youngah Do & Mark Dingemanse. 2023. Iconicity in ideophones: Guessing, memorizing, and reassessing. *Cognitive Science* e13268. 1-27. [doi: 10.1111/cogs.13268](https://onlinelibrary.wiley.com/doi/full/10.1111/cogs.13268)
\iconset{ \faLightbulb \, \faClipboardList \,  \faChartLine \,  \faPenNib }

(@)
**Van Hoey, Thomas**. 2023. ABB, a salient prototype of collocate-ideophone constructions in Mandarin Chinese. *Cognitive Linguistics* 34(1). 133-163. [doi: 10.1515/cog-2022-0031](https://doi.org/10.1515/cog-2022-0031)
\iconset{  \faUserCheck \, \faAt }

(@)
**Van Hoey, Thomas**. 2022. The blending of bending: How we engage with the World of *Avatar: The Last Airbender* through memes. *Metaphor and Symbol* 37(3). 185–207. [doi: 10.1080/10926488.2021.1973868](https://doi.org/10.1080/10926488.2021.1973868)
\iconset{  \faUserCheck \, \faAt }

(@)
Thompson, Arthur Lewis, **Thomas Van Hoey** & Youngah Do. 2021. Articulatory features of phonemes pattern to iconic meanings: Evidence from cross-linguistic ideophones. *Cognitive Linguistics* 32(4). 563-608. \* [doi: 10.1515/cog-2020-0055](https://10.1515/cog-2020-0055)
\*Editor's choice for this issue
\iconset{   \faChartLine \, \faPenNib  }


(@)
**Van Hoey, Thomas** & Arthur Lewis Thompson. 2020. The Chinese Ideophone Database (CHIDEOD). *Cahiers de Linguistique Asie Orientale* 49(2). 136–167. [doi: 10.1163/19606028-bja10006](https://doi.org/10.1163/19606028-bja10006)
\iconset{ \faLightbulb \, \faClipboardList \, \faChartLine  \, \faPenNib \,  \faAt }

(@)
**Van Hoey, Thomas**. 2018. Does the thunder roll? Mandarin Chinese meteorological expressions and their iconicity. *Cognitive Semantics* 4(2). 230-259. [doi: 10.1163/23526416-00402003](https://doi.org/10.1163/23526416-00402003)
\iconset{  \faUserCheck \, \faAt }

<!-- ## Non-refereed articles -->

<!-- ## Journalism -->

## Book chapters

(@)
Szmrecsanyi, Benedikt, Matt Hunt Gardner, Ruiming Ma & **Thomas Van Hoey**. 
*accepted*.
Empirical accountability meets theorizing about language variation. in Cukor-Avila, Patrica, Sali A. Tagliamonte & Guy Bailey (eds.) *Empirical accountability in variation linguistics: Taking the next step*. Cambridge University Press. 
\iconset{ \faLightbulb \, \faClipboardList \,  \faChartLine \,  \faPenNib \,  \faUserCheck \, \faAt }


(@)
**Van Hoey, Thomas**. 2024. Onomatopoeia in Mandarin Chinese. In Lívia Körtvélyessy & Pavol Štekauer (eds.), Onomatopoeia in the world’s languages: A comparative handbook (Comparative Handbooks of Linguistics 10), 563–575. Berlin: Mouton de Gruyter. [doi:10.1515/9783111053226-047](https://doi.org/10.1515/9783111053226-047).
\iconset{ \faUserCheck \, \faAt }

(@)
**Van Hoey, Thomas**. 2024. A semantic map for ideophones. In Thomas Fuyin Li (ed.), Handbook of Cognitive Semantics: Vol 2, 129–175. Leiden: Brill. [preprint doi: 10.31219/osf.io/muhpd](https://osf.io/muhpd/))
\iconset{  \faUserCheck \, \faAt }

(@)
**Van Hoey, Thomas** \& Chiarung Lu. 2019. Lexical variation of ideophones in Chinese classics: Their implications in embodiment and migration. In Janice Fon (ed.), *Dimensions of diffusion and diversity*, 195–226. (Cognitive Linguistics Research 63). Berlin; Boston: De Gruyter Mouton. [doi: 10.1515/9783110610895](https://doi.org/10.1515/9783110610895)
\iconset{ \faLightbulb \, \faClipboardList \,  \faChartLine \,  \faPenNib \, \faAt }


## Publications under review

(@)
Yu, Xiaoyu, Bingzi Yu, **Thomas Van Hoey**, Samuel Sui Lung Sze, Frank Lihui Tan, Tak Wang Li & Youngah Do. Phonetic substance reshapes phonological variation in language acquisition and language contact. 
<!-- Language Variation and Change -->
\iconset{   \faChartLine \,  \faPenNib }


(@)
**Van Hoey, Thomas**. Sound and lexical semantics. *Cambridge handbook of lexical semantics* (eds. Dirk Geeraerts & Dylan Glynn)
\iconset{   \faUserCheck \, \faAt }

(@)
**Van Hoey, Thomas**, Dan Dewey, Youngah Do. fNIR study on ideophone usage in Mandarin speakers.
<!-- Language and Cognition -->
\iconset{ \faLightbulb \, \faClipboardList \,  \faChartLine \,  \faPenNib \,  }

## Publications in preparation

(@) 
**Van Hoey, Thomas**, Ruiming Ma, Matt. H. Gardner & Benedikt Szmrecsanyi.
You know, like, op- optionality: Grammatical optionality does not trigger discourse markers nor repairs
<!-- Language Variation and Change. -->
\iconset{ \faLightbulb \,   \faChartLine \,  \faPenNib \,   \faAt }


(@)
**Van Hoey, Thomas**.
The lexical aspect of ideophones: A typological art as well as a Talmyan Croft
\iconset{   \faUserCheck \, \faAt }


<!-- (@) -->
<!-- Do, Youngah, Bingzi Yu & **Thomas Van Hoey**.  -->
<!-- Mitigating the trade-off between verification and speculation in learning vowel harmony.  -->
<!-- Language and Speech -->

## Theses

(@)
PhD thesis Linguistics (grade: A+) \hfill 2020 \newline
*Prototypicality and salience of Chinese ideophones: A cognitive and corpus linguistics approach* \newline
漢語擬聲(態)詞的原型與顯著特徵：以認知與語料庫語言學方法探討
\iconset{  \faUserCheck \, \faAt }

(@)
MA thesis Linguistics (grade: 17.4/20)\hfill 2015 \newline
*Ideophones in Middle Chinese: A typological study of a Tang dynasty poetic corpus* 
\iconset{   \faUserCheck \, \faAt }

<!-- >Based on a corpus of Middle Chinese poetry, I identified a set of mimetic words in Middle Chinese. I worked on an analysis of their morphological, phonological, syntactic and semantic properties, against a typological background. -->

(@)
MA thesis Sinology (grade: 18.6/20)\hfill 2014 \newline
*The *Guwen yundong 古文运动 *(Classical Prose Movement) during Tang and Song:* \newline
*Ideological as well as Stylistic Innovation?*
\iconset{  \faUserCheck \, \faAt }

<!-- >Using quantitative analyses (dendrograms, PCA, cluster analysis), I verified which authors were stylistically part of the Classical Prose Movement. This movement promoted an older style (used some four centuries or more earlier), condemning the formal style of the contemporary popular parallel prose. Unlike theoretical research hitherto suggested, my analysis shows that only a few authors formed the core of the movement. The presence of these authors fits nicely into the dominant framework of the emergence of Neo-Confucianism in the Song dynasty (10th-13th cent.). -->

## Resources and data sets

(@)
**Van Hoey, Thomas**. 2019. The Chinese ideophone database (CHIDEOD). CHIDEOD is accessible in .xlsx, .csv, .rds formats (doi: [10.17605/OSF.IO/KPWGF](https://osf.io/kpwgf/)), as well as through a [Shiny app interface](https://simazhi.shinyapps.io/chideod_appversion/).
\iconset{ \faLightbulb \, \faClipboardList \,  \faChartLine \,  \faPenNib \, \faAt }